### ISSUE TITLE
Support OPML files

### ISSUE THREAD

**Issue by bjo81** [tkem/mopidy-podcast#24]
The current procedure for adding feeds is a little annoying. It would be a great feature if mopidy-podcast could scan a directory defined in the config where OPML files can be placed.

**Comment by tkem** [comment]
I don't know anything about OPML and I don't use it, so this isn't something I'm planning to do any time soon. Contributions are welcome, of course.

**Comment by tkem** [comment]
Closing since, since it met no response.

**Comment by tkem** [comment]
This will finally be implemented for Mopidy-Podcast v2.0 ;-)
