### ISSUE TITLE
BBC Podcast RSS URLs

### ISSUE THREAD

**Issue by aspence** [tkem/mopidy-podcast#29]
Thanks again for a wonderful extension.

I'm having trouble with a BBC Podcast feed. I'm using pimusicbox 0.6, which I believe relies on this extension. I have this in my /boot/config/settings.ini:

feeds = "http://www.bbc.co.uk/programmes/p002vsnk/episodes/downloads.rss, http://www.npr.org/templates/rss/podcast.php?id=500005, http://www.npr.org/rss/rss.php?id=3"

in the [ podcasts ] section.

The middle feed, which is NPR five minute news summaries, works great. The BBC feed, however, does not. 

I used this exact URL in the Podcast Addict app on an android phone, and it worked fine.

Is this an issue with mopidy-podcast? Can i help resolve it?

I have not tried pip install -U mopidy-podcast, in case the image of pimusicbox at 0.6 used an old version of this extension. I will try that.

Thanks again for your time,
Andrew

**Comment by tkem** [comment]
Music box does us an old version, indeed, and trying to update Mopidy-Podcast may have undesirable side effects, so I wouldn't recommend it.
I'll have a look at your BBC podcast tomorrow (CET).

**Comment by aspence** [comment]
thank you!

--
Dr. Andrew Spence
Associate Professor
Department of Bioengineering
Engineering Building Room 814
College of Engineering
Temple University
1947 N. 12th St.
Philadelphia, PA 19122
Phone: 215-204-3056
Email: aspence@temple.edu
www.spencelab.com

**Comment by tkem** [comment]
I tried http://www.bbc.co.uk/programmes/p002vsnk/episodes/downloads.rss with current versions of Mopidy and Mopidy-Podcast and it plays just fine.
I'm not an expert on the musicbox `settings.ini` format, but looking at the default settings in https://github.com/pimusicbox/pimusicbox/blob/develop/filechanges/boot/config/settings.ini I think you don't use quotation marks when specifying multiple parameters. You may try that, and if that doesn't help, I'd suggest posting this issue on http://discuss.mopidy.com; there are quite a few musicbox users and developers there.

**Comment by aspence** [comment]
genius!

removed quotes, comma only, single line:

feeds = http://www.bbc.co.uk/programmes/p002vsnk/episodes/downloads.rss, http://www.npr.org/templates/rss/podcast.php?id=500005, http://www.npr.org/templates/rss/podlayer.php?=3

works a treat.

thanks for taking a look so quickly.

cheers!
