### ISSUE TITLE
Create Debian package for Mopidy-Podcast v2.0.

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-podcast#36]
@jodal: would be awesome if you could find the time, especially since the `mopidy-podcast` version on `apt.mopidy.com` now differs considerably from what's described on http://mopidy-podcast.readthedocs.io/en/latest/...

**Comment by jodal** [comment]
What's the required changes?

- New version
- Breaks/deprecates mopidy-podcast-gpodder and mopidy-podcast-itunes
- Should create `/etc/mopidy/podcast` directory, no config change required

**Comment by tkem** [comment]
mopidy-podcast-gpodder has been officially deprecated and won't be maintained any longer (at least not by me). Question is how to deal with such a situation wrt. Debian packages. How did you deal with Mopidy-Local-Whoosh? Were there ever Debian packages prepared for that?

As for mopidy-podcast-itunes, v2.0.0 (if packaged) will work with mopidy-podcast v2.0. 

Frankly, I'm not sure how to express these with Debian dependency control fields. At least not without resorting to something like naming it `mopidy-podcast-2`... However, similar questions will arise when Mopidy drops support for some deprecated backend APIs in v3.0, AFAICs.

**Comment by tkem** [comment]
Thinking a little more about this, mopidy-podcast v2.0 actually `Replaces` mopidy-podcast-gpodder, since most of its current/previous functionality can be achieved by putting links to gpodder.net in your `Podcasts.opml`. So this may be the way to go.

**Comment by tkem** [comment]
Having another look at the Debian Policy manual, I think this should do it:
```
Breaks: mopidy-podcast-gpodder, mopidy-podcast-itunes (<< 2.0)
```
If I understand correctly, people who installed gpodder will have to uninstall it manually before upgrading, which is probably OK.

**Comment by jodal** [comment]
New packages have now been uploaded. Source has moved to:

- https://anonscm.debian.org/git/pkg-mopidy/mopidy-podcast.git/
- https://anonscm.debian.org/git/pkg-mopidy/mopidy-podcast-itunes.git/

**Comment by tkem** [comment]
Great, thanks!
