### ISSUE TITLE
Support TuneIn/RadioTime "audio" OPML type

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-podcast#41]
https://github.com/brianhornsby/plugin.audio.tuneinradio/wiki/RadioTime-API-Methods:-Browse

**Comment by dubaleeiro** [comment]
Could you please provide another valid link? This seems to be invalid... thanks!

**Comment by tkem** [comment]
No: https://brianhornsby.com/blog/#dmca-takedown-notice
So, screw TuneIn.
