### ISSUE TITLE
Skip cache for local feeds

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-podcast#42]
It may be preferable to _not_ cache local files, like the "root" OPML file, so changes are available immediately.
This would require bypassing `PodcastFeedCache` on a per-scheme basis or changing the current implementation to selectively store values in `__missing__` (requiring `cachetools` >= 2).

**Comment by jjok** [comment]
I think skipping the cache altogether would make most sense. Wouldn't it?

**Comment by tkem** [comment]
@jjok: No.
