### ISSUE TITLE
  Found podcast configuration errors, the extension has been automatically disabled:

### ISSUE THREAD

**Issue by gerroon** [tkem/mopidy-podcast#44]
Hi

Mopidy 2.1 on Debian Testing.

I do not understand these erros, I copied the default config from the doc site and pasted in mopidy config :(

It is literally the default config. I disabled all other to test it out (except those 2) and Is till get error. 

Is this a version issue?

thanks

WARNING  Found podcast configuration errors, the extension has been automatically disabled:
WARNING    podcast/browse_root unknown config key.
WARNING    podcast/browse_order unknown config key.

**Comment by tkem** [comment]
Does this also happen on Debian stable?

**Comment by gerroon** [comment]
@tkem I would not know that because I only have Testing

**Comment by jjok** [comment]
Where did you get the default configuration from?

You can see the expected configuration for the latest version here: https://github.com/tkem/mopidy-podcast/blob/master/mopidy_podcast/ext.conf

The warnings say that your config doesn't have `browse_root` or `browse_order`.

**Comment by tkem** [comment]
Thanks @jjok - I didn't read much further then "Debian testing" ;-)

@gerroon: There's no need to paste an extension's default configuration into `mopidy.conf` - these are included in the extension package itself. Only if you want to change some settings, these can be overridden in `mopidy.conf`.

**Comment by gerroon** [comment]
@jjok

This is where I got from

https://mopidy-podcast.readthedocs.io/en/latest/config.html

**Comment by gerroon** [comment]
@tkem 
Still, even adding only a single config line for the podcast addon makes the addon disabled. Either my python has some issues with what the actual code wants or I am just a stupid dumb duck.

**Comment by tkem** [comment]
Well, what version of mopidy-podcast do you actually have installed? If it's <2.0, adding these settings to your mopidy.conf won't work, since they were added in v2.0, IIRC.
