### ISSUE TITLE
ERROR    Podcast lookup failed for 

### ISSUE THREAD

**Issue by gerroon** [tkem/mopidy-podcast#45]
Mopidy 2.1 Debian Testing

Icant play any podcast whatsoever browsing Itunes or GPodder. I am either hitting non existing shows or there is an issue with the podcasts browser.

I only have 

[podcast]
enabled = true

Other options throws errors like I mentioned in the previous bug.

ERROR    Podcast lookup failed for podcast+http://feeds.podtrac.com/zKq6WZZLTlbM#https://dts.podtrac.com/redirect.mp3/rss.art19.com/episodes/584b2fb4-1309-4370-a810-7e98e7c9d59b.mp3: object of type 'generator' has no len()

**Comment by tkem** [comment]
Which version of mopidy-podcast are you using? GPodder support has been dropped as of mopidy-podcast v2.0.

**Comment by tkem** [comment]
Also the URI scheme has changed, using episode GUIDs instead of enclosure URLs for fragments.

**Comment by gerroon** [comment]
I am using the podcast addons browser, these are not my own podcasts. 

How do I tell which version of podcast I am running?

**Comment by tkem** [comment]
https://docs.mopidy.com/en/latest/troubleshooting/#show-installed-dependencies

**Comment by tkem** [comment]
Can we close this?
