### ISSUE TITLE
FR: Sort by date

### ISSUE THREAD

**Issue by gerroon** [tkem/mopidy-podcast#49]
Hi

Most podcast apps will let you sort by date and I think that it makes sense since one will want to see the updated feeds first. It would be nice if there is a way to see the updated podcasts. Not all podcasts updated even regularly and with a long podcast list it makes hard to find what is updated. I have to click on a podcast and see if it had any updates atm.

thanks

**Comment by jjok** [comment]
So, have an option in the config to order by most recently updated, and that reorders the podcasts?

**Comment by tkem** [comment]
There are already options to configure the [browse](http://mopidy-podcast.readthedocs.io/en/latest/config.html#confval-podcast/browse_order) and [lookup](http://mopidy-podcast.readthedocs.io/en/latest/config.html#confval-podcast/lookup_order) order for RSS feeds.
AFAIK, OPML files don't have a "last updated" attribute, so they can't be sorted. Even if they had, this would not be very useful for local/exported OPML files.
