### ISSUE TITLE
Possibility to add url for a item without knowing guid

### ISSUE THREAD

**Issue by skogsmaskin** [tkem/mopidy-podcast#50]
What would be awesome is to support adding a url like this:

``podcast+http://podkast.nrk.no/program/dagsnytt.rss#item[0]``

for playing the most recent episode (or a specific item number in the list)

Trying to automate something that will play the latest episode from a feed.

**Comment by tkem** [comment]
First of all, sorry this took so long!
Secondly, sorry, but I think (mis)using the URI fragment for completely different things would make this all more complicated and error-prone.
Couldn't you just retrieve all items in the podcast and then select the first (or last, or whetever) entry yourself?
