### ISSUE TITLE
Resume does not work 

### ISSUE THREAD

**Issue by gerroon** [tkem/mopidy-podcast#52]
Hi

When I pause and resume a podcast (after couple minutes in pause ), the podcast playback does not resume at all. It says it is playing but no sound coming from Mopidy. If I just forward the stream couple seconds ahead (in ncmpcpp pressing "f" couple times)  then it starts playing properly again

I am on Debian Testing using Mopidy 2.1.0-2 (output = pulsesink server=127.0.0.1) 

I am not sure if this is an issue with the podcast addon or an issue with the way streaming is done in Mopidy but in any case I thought I would start reporting it here.

thanks

**Comment by tkem** [comment]
Since mopidy-podcast has nothing to do with pausing/resuming (it basically just forwards the episodes URL to Mopidy), I'm afraid there's nothing I can do about this.
