### ISSUE TITLE
Is it possible to continue playback of episodes where you left off previously?

### ISSUE THREAD

**Issue by riher** [tkem/mopidy-podcast#53]
I don't know if mopidy extensions are capable of something like this but to me, this is an integral function of podcast apps and would be super useful.

**Comment by tkem** [comment]
PRs welcome!

**Comment by jjok** [comment]
@riher If you mean when you switch off and on again, then there's an option in Mopidy to restore the previous state which may do what you want.

https://docs.mopidy.com/en/latest/config/#confval-core/restore_state

**Comment by tkem** [comment]
@jjok: Thanks, completely forgot about this since I never used it myself.

**Comment by riher** [comment]
What I want mopidy to do is to continue playback for _every_ episode that was previously listened to at the position it stopped. Whenever I click the episode.

After talking to adamcik in irc I'm now preparing a PR for the mopidy core as it's apparently not a feature suited for a backend extension.
