### ISSUE TITLE
Add support for seeking and duration display

### ISSUE THREAD

**Issue by de666** [tkem/mopidy-podcast#55]
As far I can see, if I play a podcast fie (mp3 stream) through this extension it is not possible to seek the mp3  file furthermore the length it is not displayed.
On the other hand If I put the streaming url directly in mopidy as a stream, it is possible to seek the file and to see how it lasts.
I'm wondering about the reason of this different behaviour and if it is possible to add this capability to this extension.
Thankyou

**Comment by tkem** [comment]
Cannot reproduce - AFAICS, seeking and duration display works with podcasts as well, at least with Mopidy Mobile:

![image](https://user-images.githubusercontent.com/2833077/42835773-e8fe613a-89f9-11e8-932b-4c6944301767.png)

Maybe there is an issue with your podcast's metadata or your client - have you tried other podcasts?

**Comment by de666** [comment]
I think it is related to the `itunes:duration` tag. If this tag is present the length is displayed correctly and the seeking is possible, viceversa if this tag is missing, it is not possible to seek the podcast, however (as I wrote before), if you paste the mp3 url inside mopidy as a stream, the seeking magically appears.
Try this podcast `https://www.deejay.it/api/tool/itunes.php?id=549937` to see an example of what I'm talking about (and I think only a few podcasts have that tag).

**Comment by tkem** [comment]
That's how it's supposed to work - if the feed doesn't contain the required metada, there's nothing this extension can do about it.
